### ISSUE TITLE
404 on http://naso.github.io/zero/

### ISSUE THREAD

**Issue by laurent-d** [naso/zero#1]
The demo page return a 404 page  > http://naso.github.io/zero/
Thanks for your work

Regards

**Comment by naso** [comment]
Hey Laurent!

Thanks for the feedback. It is indeed. Sorry about that.
I am working on it right now, so it is going through a process of a big refactor / restructure. I will need a few more days.

Will let you know when it is ready.

**Comment by naso** [comment]
Updated: http://naso.github.io/zero/
